# Generated by Django 4.2.30 on 2026-06-16 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_change', models.IntegerField(help_text='Signed delta applied to available_quantity')),
                ('reserved_change', models.IntegerField(help_text='Signed delta applied to reserved_quantity')),
                ('available_after', models.PositiveIntegerField()),
                ('reserved_after', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('RESTOCK', 'Restock'), ('ADJUSTMENT', 'Manual adjustment'), ('ALLOCATION', 'Reserved by allocation'), ('CANCELLATION', 'Released by cancellation'), ('FULFILLMENT', 'Removed by fulfillment')], max_length=32)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.sku')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.CheckConstraint(check=models.Q(('available_quantity__gte', 0)), name='sku_available_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.CheckConstraint(check=models.Q(('reserved_quantity__gte', 0)), name='sku_reserved_non_negative'),
        ),
    ]
