# Generated by Django 4.2.30 on 2026-06-16 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('backorder_on_shortage', models.BooleanField(default=True)),
                ('orders_processed', models.PositiveIntegerField(default=0)),
                ('orders_allocated', models.PositiveIntegerField(default=0)),
                ('orders_backordered', models.PositiveIntegerField(default=0)),
                ('detail', models.JSONField(blank=True, default=list)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
